import { z } from 'zod';

/**
 * Registration schema
 */
export const registerSchema = z.object({
  username: z
    .string()
    .min(3, 'Username must be at least 3 characters')
    .max(30, 'Username must be at most 30 characters')
    .regex(
      /^[a-zA-Z0-9_.-]+$/,
      'Username can only contain letters, numbers, dots, underscores, and hyphens'
    ),
  email: z.string().email('Invalid email address'),
  password: z
    .string()
    .min(8, 'Password must be at least 8 characters')
    .max(128, 'Password must be at most 128 characters'),

  // Optional: E2EE keys generated by client
  identityKeyPublic: z.string().optional(),
  signedPreKeyPublic: z.string().optional(),
  signedPreKeySignature: z.string().optional(),
});

export type RegisterInput = z.infer<typeof registerSchema>;

/**
 * Login schema
 */
export const loginSchema = z.object({
  identifier: z.string().min(1, 'Username or email is required'),
  password: z.string().min(1, 'Password is required'),
});

export type LoginInput = z.infer<typeof loginSchema>;

/**
 * Refresh token schema
 */
export const refreshTokenSchema = z.object({
  refreshToken: z.string().min(1, 'Refresh token is required'),
});

export type RefreshTokenInput = z.infer<typeof refreshTokenSchema>;

/**
 * Public ID lookup schema
 */
export const publicIdSchema = z.object({
  publicId: z.string().min(1, 'Public ID is required'),
});

export type PublicIdInput = z.infer<typeof publicIdSchema>;
